### PR TITLE
BinarySearchTree

### LINKED ISSUE #4: add BST
Add implementation for BST.

### PR DESCRIPTION
**Pull request by mr-siddy**
Implementation of Binary Search Tree in C# :smiley: ,So that developers could find resources for C# easily

### CODE REVIEW

**Comment by farQtech** [comment]
@mr-siddy thanks for the contribution, can you comment on the related issue as well so that I can assign that to you.

**Comment by farQtech** [comment]
Also can you add an interface in the same file for the implementation. And if you want this pr to be counted as a contribution for hacktoberfest, you would have to open it after October 1st [more info here](https://hacktoberfest.digitalocean.com/)

**Review by farQtech — CHANGES_REQUESTED** [review]
Add interface for the implementation

**Comment by mr-siddy** [comment]
Okay I will try to add an interface for implementation and then open again on 1 October , thanks for suggesion and advice

**Pull request closed without merging**
